# Generated by Django 2.2 on 2020-09-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200924_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', help_text='Enter the language of the book', max_length=2),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
